### ISSUE TITLE
Please re-enable certificate checking

### ISSUE THREAD

**Issue by dfoxfranke** [WebEnchanter/nixos-bootstrapper#5]
`*.githubusercontent.com` is in Github's certificate as a Subject Alternative Name. Modern versions of `wget` (since 2011) should have no problem validating it. Please put certificate checking on by default and, if you need to support older versions of `wget`, add a configuration option to turn it off. You could also try using `curl`, which has supported SANs for much longer.

**Comment by rushmorem** [comment]
Good point. Will try `curl` instead. Thanks!
